const fs = require('fs');
const path = require('path');
const { createCanvas, loadImage } = require('canvas');

const WATERMARK_TEXT = 'Generated by PixelCraft AI';
const WATERMARK_FONT_SIZE = 24;
const WATERMARK_OPACITY = 0.7;
const WATERMARK_POSITION = 'bottom-right';

// Add watermark to image
async function addWatermark(imageBuffer, options = {}) {
  const {
    text = WATERMARK_TEXT,
    fontSize = WATERMARK_FONT_SIZE,
    opacity = WATERMARK_OPACITY,
    position = WATERMARK_POSITION
  } = options;

  try {
    const image = await loadImage(imageBuffer);
    const canvas = createCanvas(image.width, image.height);
    const ctx = canvas.getContext('2d');

    // Draw original image
    ctx.drawImage(image, 0, 0);

    // Setup watermark style
    ctx.globalAlpha = opacity;
    ctx.font = `${fontSize}px Arial`;
    ctx.fillStyle = '#ffffff';
    ctx.strokeStyle = '#000000';
    ctx.lineWidth = 2;

    // Calculate position
    const textMetrics = ctx.measureText(text);
    const padding = 20;
    let x, y;

    switch (position) {
      case 'bottom-right':
        x = image.width - textMetrics.width - padding;
        y = image.height - padding;
        break;
      case 'bottom-left':
        x = padding;
        y = image.height - padding;
        break;
      case 'top-right':
        x = image.width - textMetrics.width - padding;
        y = fontSize + padding;
        break;
      case 'top-left':
        x = padding;
        y = fontSize + padding;
        break;
      case 'center':
        x = (image.width - textMetrics.width) / 2;
        y = image.height / 2;
        break;
      default:
        x = image.width - textMetrics.width - padding;
        y = image.height - padding;
    }

    // Draw watermark with shadow for visibility
    ctx.shadowColor = 'rgba(0, 0, 0, 0.5)';
    ctx.shadowBlur = 4;
    ctx.shadowOffsetX = 2;
    ctx.shadowOffsetY = 2;

    // Draw text stroke first (for better visibility)
    ctx.strokeText(text, x, y);
    
    // Draw text fill
    ctx.fillText(text, x, y);

    // Reset shadow
    ctx.shadowColor = 'transparent';
    ctx.globalAlpha = 1;

    return canvas.toBuffer('image/png');
  } catch (error) {
    console.error('Watermark error:', error);
    return imageBuffer;
  }
}

// Check if watermark should be added based on user status
async function processImageWithWatermark(imageBuffer, isPremium, userId) {
  if (isPremium) {
    // Premium users get no watermark
    return imageBuffer;
  }
  return addWatermark(imageBuffer);
}

// Get watermark configuration
function getWatermarkConfig(isPremium, customOptions = {}) {
  if (isPremium) {
    return { enabled: false };
  }

  return {
    enabled: true,
    text: customOptions.text || WATERMARK_TEXT,
    fontSize: customOptions.fontSize || WATERMARK_FONT_SIZE,
    opacity: customOptions.opacity || WATERMARK_OPACITY,
    position: customOptions.position || WATERMARK_POSITION
  };
}

module.exports = {
  addWatermark,
  processImageWithWatermark,
  getWatermarkConfig,
  WATERMARK_TEXT
};